/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.text.DefaultEditorKit;
import zooclassificator.engine.KNearest;
import zooclassificator.engine.NaiveBayes;
import zooclassificator.model.Pair;

/**
 *
 * @author Ahmad Naufal Farhan
 */
public class AppUI extends javax.swing.JFrame {
    
    File file;

    /**
     * Creates new form AppUI
     */
    public AppUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataFileChooser = new javax.swing.JFileChooser();
        buttonGroupAlgorithm = new javax.swing.ButtonGroup();
        buttonGroupTrain = new javax.swing.ButtonGroup();
        textFilePath = new javax.swing.JTextField();
        buttonSubmit = new javax.swing.JButton();
        buttonBrowse = new javax.swing.JButton();
        radioAlgorithm2 = new javax.swing.JRadioButton();
        radioAlgorithm1 = new javax.swing.JRadioButton();
        radioTrain1 = new javax.swing.JRadioButton();
        radioTrain2 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        textK = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textResult = new javax.swing.JTextPane();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        dataFileChooser.setDialogTitle("Select a Dataset");
        dataFileChooser.setFileFilter(new FileFilter() {

            public String getDescription() {
                return "Dataset Documents (txt, arff)";
            }

            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else {
                    return f.getName().toLowerCase().endsWith(".txt") || f.getName().toLowerCase().endsWith(".arff");
                }
            }
        });

        buttonGroupAlgorithm.add(radioAlgorithm1);
        buttonGroupAlgorithm.add(radioAlgorithm2);

        buttonGroupTrain.add(radioTrain1);
        buttonGroupTrain.add(radioTrain2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ZooHoo");
        setResizable(false);

        textFilePath.setEditable(false);
        textFilePath.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        textFilePath.setText("Browse a file...");
        textFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFilePathActionPerformed(evt);
            }
        });

        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });

        buttonBrowse.setText("Browse..");
        buttonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBrowseActionPerformed(evt);
            }
        });

        radioAlgorithm2.setText("Naive-Bayes");
        radioAlgorithm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAlgorithm2ActionPerformed(evt);
            }
        });

        radioAlgorithm1.setText("k-Nearest Neighbor (kNN)");
        radioAlgorithm1.setSelected(true);
        radioAlgorithm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAlgorithm1ActionPerformed(evt);
            }
        });

        radioTrain1.setText("Full Training");
        radioTrain1.setSelected(true);

        radioTrain2.setText("10-fold Cross-Validation");

        textK.setText("1");

        textResult.setEditable(false);
        textResult.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N
        jScrollPane1.setViewportView(textResult);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Classification Algorithm");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Training Method");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioAlgorithm1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textK, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(radioAlgorithm2)
                                    .addComponent(jLabel1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonBrowse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioTrain1)
                                    .addComponent(radioTrain2)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator2)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBrowse)
                    .addComponent(buttonSubmit)
                    .addComponent(textFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAlgorithm1)
                    .addComponent(radioTrain1)
                    .addComponent(textK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAlgorithm2)
                    .addComponent(radioTrain2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(373, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        textResult.setText("Waiting...");
        if (!textFilePath.getText().equals("Browse a file...")) {
            try {
                // TODO add your handling code here:
                String text;
                Pair P = Pair.readDataSet(file.getAbsolutePath());
                if (radioAlgorithm2.isSelected()) {
                    NaiveBayes nb = new NaiveBayes();
                    if (radioTrain2.isSelected())
                        text = nb.ten_fold(P);
                    else
                        text = nb.fulltraining(P);
                } else if (radioAlgorithm1.isSelected()) {
                    int k = Integer.parseInt(textK.getText());
                    KNearest knn = new KNearest(k);
                    if (radioTrain2.isSelected())
                        text = knn.tenFold(P);
                    else
                        text = knn.FullTraining(P);
                } else {
                    text = "Oops error occurred..";
                }

                textResult.setText(text);
            } catch (IOException ex) {
                Logger.getLogger(AppUI.class.getName()).log(Level.SEVERE, null, ex);
                textResult.setText("I/O Error...");
            }
        } else {
            textResult.setText("Please select a dataset!");
        }
    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void textFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFilePathActionPerformed

    private void buttonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBrowseActionPerformed
        // TODO add your handling code here:
        int ret = dataFileChooser.showOpenDialog(this);
        
        if (ret == JFileChooser.APPROVE_OPTION) {
            file = dataFileChooser.getSelectedFile();
            // What to do with the file, e.g. display it in a TextArea
            textFilePath.setText(file.getAbsolutePath());
        } else {
            System.out.println("File access cancelled by user.");
        }

    }//GEN-LAST:event_buttonBrowseActionPerformed

    private void radioAlgorithm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAlgorithm1ActionPerformed
        // TODO add your handling code here:
        textK.setEditable(true);
    }//GEN-LAST:event_radioAlgorithm1ActionPerformed

    private void radioAlgorithm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAlgorithm2ActionPerformed
        // TODO add your handling code here:
        textK.setEditable(false);
    }//GEN-LAST:event_radioAlgorithm2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBrowse;
    private javax.swing.ButtonGroup buttonGroupAlgorithm;
    private javax.swing.ButtonGroup buttonGroupTrain;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JFileChooser dataFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton radioAlgorithm1;
    private javax.swing.JRadioButton radioAlgorithm2;
    private javax.swing.JRadioButton radioTrain1;
    private javax.swing.JRadioButton radioTrain2;
    private javax.swing.JTextField textFilePath;
    private javax.swing.JTextField textK;
    private javax.swing.JTextPane textResult;
    // End of variables declaration//GEN-END:variables
}
