/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import zooclassificator.engine.KNearest;
import zooclassificator.engine.NaiveBayes;
import zooclassificator.model.Data;
import zooclassificator.model.Pair;

/**
 *
 * @author Ahmad Naufal Farhan
 */
public class ClassificateUI extends javax.swing.JFrame {

    File file;
    ArrayList<JCheckBox> checkBox = new ArrayList<>();
    /**
     * Creates new form ClassificateUI
     */
    public ClassificateUI() {
        initComponents();
        checkBox = new ArrayList<>();
        checkBox.add(properties1);
        checkBox.add(properties2);
        checkBox.add(properties3);
        checkBox.add(properties4);
        checkBox.add(properties5);
        checkBox.add(properties6);
        checkBox.add(properties7);
        checkBox.add(properties8);
        checkBox.add(properties9);
        checkBox.add(properties10);
        checkBox.add(properties11);
        checkBox.add(properties12);
        checkBox.add(properties14);
        checkBox.add(properties15);
        checkBox.add(properties16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataFileChooser = new javax.swing.JFileChooser();
        jSeparator1 = new javax.swing.JSeparator();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        buttonSubmit = new javax.swing.JButton();
        labelResult = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        properties1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        properties2 = new javax.swing.JCheckBox();
        properties3 = new javax.swing.JCheckBox();
        properties4 = new javax.swing.JCheckBox();
        properties5 = new javax.swing.JCheckBox();
        properties6 = new javax.swing.JCheckBox();
        properties7 = new javax.swing.JCheckBox();
        properties8 = new javax.swing.JCheckBox();
        properties9 = new javax.swing.JCheckBox();
        properties10 = new javax.swing.JCheckBox();
        properties11 = new javax.swing.JCheckBox();
        properties12 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        properties14 = new javax.swing.JCheckBox();
        properties15 = new javax.swing.JCheckBox();
        properties16 = new javax.swing.JCheckBox();
        comboProperties13 = new javax.swing.JComboBox<>();
        radioAlgorithm1 = new javax.swing.JRadioButton();
        radioAlgorithm2 = new javax.swing.JRadioButton();
        textK = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        buttonBrowse = new javax.swing.JButton();
        textFilePath = new javax.swing.JTextField();

        buttonGroup1.add(radioAlgorithm1);
        buttonGroup1.add(radioAlgorithm2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        buttonSubmit.setText("Classify!");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });

        labelResult.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Your animal name!");

        properties1.setText("Hairy");
        properties1.setOpaque(false);

        jLabel2.setText("Animal Properties");

        properties2.setText("Feathers");
        properties2.setOpaque(false);

        properties3.setText("Lays Eggs");
        properties3.setOpaque(false);

        properties4.setText("Has Milk");
        properties4.setOpaque(false);

        properties5.setText("It flies!");
        properties5.setOpaque(false);

        properties6.setText("It swims!");
        properties6.setOpaque(false);

        properties7.setText("Predator");
        properties7.setOpaque(false);

        properties8.setText("Has Teeth");
        properties8.setOpaque(false);

        properties9.setText("Vertebrae");
        properties9.setOpaque(false);

        properties10.setText("Breathes");
        properties10.setOpaque(false);

        properties11.setText("Venomous");
        properties11.setOpaque(false);

        properties12.setText("Fins");
        properties12.setOpaque(false);

        jLabel3.setText("How many Legs?");

        properties14.setText("Has Tail");
        properties14.setOpaque(false);

        properties15.setText("Domestic");
        properties15.setOpaque(false);

        properties16.setText("Catsize?");
        properties16.setOpaque(false);

        comboProperties13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "2", "4", "5", "6", "8" }));

        radioAlgorithm1.setText("k-Nearest Neighbor (kNN)");
        radioAlgorithm1.setSelected(true);
        radioAlgorithm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAlgorithm1ActionPerformed(evt);
            }
        });

        radioAlgorithm2.setText("Naive-Bayes");
        radioAlgorithm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAlgorithm2ActionPerformed(evt);
            }
        });

        textK.setText("1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Classification Algorithm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radioAlgorithm1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textK, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(radioAlgorithm2)
                            .addComponent(jLabel4))
                        .addGap(61, 61, 61))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(properties1)
                                    .addComponent(properties2)
                                    .addComponent(properties3)
                                    .addComponent(properties14))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(properties15)
                                        .addGap(18, 18, 18)
                                        .addComponent(properties16))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(properties4)
                                            .addComponent(properties5)
                                            .addComponent(properties6))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(properties7)
                                            .addComponent(properties8)
                                            .addComponent(properties9))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(properties12)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(properties10)
                                                    .addComponent(properties11))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(comboProperties13, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(93, 93, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioAlgorithm1)
                            .addComponent(textK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioAlgorithm2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(properties1)
                    .addComponent(properties4)
                    .addComponent(properties7)
                    .addComponent(properties10)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(properties2)
                    .addComponent(properties5)
                    .addComponent(properties8)
                    .addComponent(properties11)
                    .addComponent(comboProperties13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(properties3)
                    .addComponent(properties6)
                    .addComponent(properties9)
                    .addComponent(properties12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(properties14)
                    .addComponent(properties15)
                    .addComponent(properties16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonBrowse.setText("Browse..");
        buttonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBrowseActionPerformed(evt);
            }
        });

        textFilePath.setEditable(false);
        textFilePath.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        textFilePath.setText("Select the zoo.data.arff file path...");
        textFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFilePathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(labelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(textFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonBrowse)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(labelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonBrowse)
                        .addComponent(buttonSubmit)
                        .addComponent(textFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(82, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFilePathActionPerformed

    private void buttonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBrowseActionPerformed
        // TODO add your handling code here:
        int ret = dataFileChooser.showOpenDialog(this);

        if (ret == JFileChooser.APPROVE_OPTION) {
            file = dataFileChooser.getSelectedFile();
            // What to do with the file, e.g. display it in a TextArea
            textFilePath.setText(file.getAbsolutePath());
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_buttonBrowseActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        
        if (!textFilePath.getText().equals("Select the zoo.data.arff file path...")) {
            labelResult.setText("Waiting...");
            try {
                Pair dataset = Pair.readDataSet(file.getAbsolutePath());
                ArrayList<String> Data = new ArrayList<>();
                
                int j=0; //nilai iterasi untuk checkbox
                
                //Loop ini akan melakukan inisialisasi Data yang akan dijadikan test mulai dari atribut 1-18
                for (int i=0; i<dataset.getAttrLib().size()-1; i++){
                    //Bagian kondisi ini untuk memisahkan pengambilan data dari textfield, combo, atau checkbox
                    if (i == 0) {
                        //Khusus data pertama harus berasal dari textfield
                        Data.add(jTextField1.getText());  
                    } else if(i == 13) {
                        //Khusus data ke 14 berasal dari combo
                        Data.add(comboProperties13.getSelectedItem().toString());
                    } else { 
                        //Data checkbox akan di iterasi disini
                        if (checkBox.get(j++).isSelected()){
                            Data.add("1");
                        } else {
                            Data.add("0");
                        }
                    }
                } //akhir inisialisasi. data dari form berhasil diinput ke struktur data
                
                //sesuaikan if else nya dengan pilihan knn/naivebayes
                //Mulai pengklasifikasian
                String result;
                Data newData = new Data(Data);
                if (radioAlgorithm1.isSelected()) { //Jika KNN
                    int n = Integer.parseInt(textK.getText()); //KNN untuk 5NN
                    KNearest knn = new KNearest(n);
                    result = knn.Classificate(dataset, newData);
                } else { //Jika Naive Bayes
                    NaiveBayes nb = new NaiveBayes();
                    nb.init(dataset);
                    result = nb.test(newData);
                }
                System.out.println(result);
                labelResult.setText("Result: " + result);
                
                /********* SAMPAI SINI BENERIN **********/
            } catch (IOException ex) {
                Logger.getLogger(ClassificateUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            labelResult.setText("Please input your arff file");
        }
    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void radioAlgorithm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAlgorithm1ActionPerformed
        // TODO add your handling code here:
        textK.setEditable(true);
    }//GEN-LAST:event_radioAlgorithm1ActionPerformed

    private void radioAlgorithm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAlgorithm2ActionPerformed
        // TODO add your handling code here:
        textK.setEditable(false);
    }//GEN-LAST:event_radioAlgorithm2ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ClassificateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ClassificateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ClassificateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ClassificateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ClassificateUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBrowse;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JComboBox<String> comboProperties13;
    private javax.swing.JFileChooser dataFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelResult;
    private javax.swing.JCheckBox properties1;
    private javax.swing.JCheckBox properties10;
    private javax.swing.JCheckBox properties11;
    private javax.swing.JCheckBox properties12;
    private javax.swing.JCheckBox properties14;
    private javax.swing.JCheckBox properties15;
    private javax.swing.JCheckBox properties16;
    private javax.swing.JCheckBox properties2;
    private javax.swing.JCheckBox properties3;
    private javax.swing.JCheckBox properties4;
    private javax.swing.JCheckBox properties5;
    private javax.swing.JCheckBox properties6;
    private javax.swing.JCheckBox properties7;
    private javax.swing.JCheckBox properties8;
    private javax.swing.JCheckBox properties9;
    private javax.swing.JRadioButton radioAlgorithm1;
    private javax.swing.JRadioButton radioAlgorithm2;
    private javax.swing.JTextField textFilePath;
    private javax.swing.JTextField textK;
    // End of variables declaration//GEN-END:variables
}
